# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dcbd5405685a49f2a8ee05e519818fd2f75ddebd7f0adb68aa6b68e6763037b7729c8379374323d11c0dd274ef3e3381e78c90b3c33aafbdb1a6865782934c1

test:
  secret_key_base: 05bcc79e74c23e615477bb38e113b3e031a227a912449acfa97514ddbd8b9f4a94d3ab6e8e2ef015d8a592e34ecc14aa7b7aa09b5d0f274162e902582a1243c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
